[build]
builder = "nixpacks"
buildCommand = "python -m pip install -r requirements.txt"

[deploy]
startCommand = "celery -A app worker --loglevel=info -E"

[variables]
RAILWAY_ENVIRONMENT_NAME = "production"